## cartridge.properties for cartridge plugin_pulpoar
#Fri Feb 7 11:56:14 CEST 2025
demandware.cartridges.app_dept_base.multipleLanguageStorefront=true
demandware.cartridges.plugin_pulpoar.id=plugin_pulpoar
demandware.cartridges.plugin_pulpoar.version=1.0.0
